name: incubapp_lite
description: A new Flutter project.

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.1.0
  http: ^1.1.0
  font_awesome_flutter: 11.0.0
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  flutter_inappwebview: ^6.1.5
  android_intent_plus: ^5.3.1
  meta: ^1.15.0
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_launcher_icons:

  android: true
  image_path: "assets/icono.png"


flutter:

  assets:
    - assets/logo.png
    - assets/icono.png

  uses-material-design: true

